spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/splitbill
    username: splitbill
    password: splitbill
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    open-in-view: false